url: https://quickbyte.github.io
baseurl: ''

# Site settings
title: QuickByte
email: quickbytekenya@gmail.com
description: "QuickByte Technologies is a Nairobi based Digital Agency that specializes in website design, custom development, mobile apps and email marketing."


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/quickbytekenya
  - title: facebook
    url: http://facebook.com/quickbytekenya 

# Postal address (add as many lines as necessary)
address:
  - line: 40336 - 00100
  - line: Langata Otiende, Nairobi

# Build settings
markdown: kramdown
permalink: pretty

gems:
      - jekyll-sitemap



      
